### ISSUE TITLE
DockerHub Repository not shown in wizard

### ISSUE THREAD

**Issue by derPuntigamer** [swarmpit/swarmpit#173] opened 2017-11-07 22:28 UTC
I have a freshly created public repository on DockerHub (a few hours old) and it does not shows in the search. First, I've created a repository with a false name (typo) and somehow, the old and deleted repository still shows in the search. How the query is performed? Is there an own DB for the public DockerHub repos?

**Comment by derPuntigamer** [comment] 2017-11-07 22:32
logs from the DB container:

```
swarmpit_db.1.l058rwy5g5iz@v22017054633349468 [error] 2017-11-07T22:29:54.244501Z nonode@nohost emulator -------- Error in process <0.12257.0> with exit value: {database_does_not_exist,[{mem3_shards,load_shards_from_db,"_users",[{file,"src/mem3_shards.erl"},{line,327}]},{mem3_shards,load_shards_from_disk,1,[{file,"src/mem3_shards.erl"},{line,315}]},{mem3_shards,load_shards_from_disk...
swarmpit_db.1.l058rwy5g5iz@v22017054633349468 [notice] 2017-11-07T22:29:54.244534Z nonode@nohost <0.326.0> -------- chttpd_auth_cache changes listener died database_does_not_exist at mem3_shards:load_shards_from_db/6(line:327) <= mem3_shards:load_shards_from_disk/1(line:315) <= mem3_shards:load_shards_from_disk/2(line:331) <= mem3_shards:for_docid/3(line:87) <= fabric_doc_open:go/3(line:38) <= chttpd_auth_cache:ensure_auth_ddoc_exists/2(line:187) <= chttpd_auth_cache:listen_for_changes/1(line:134)
```

**Comment by derPuntigamer** [comment] 2017-11-08 07:55
It seems time solved the problem. Anyway, is there a way to force synchronizing DockerHub?

**Comment by nohaapav** [comment] 2017-11-08 09:43
@derPuntigamer Hi Daniel, I will try to reproduce your issue. Public repositories are fetched via official [API](https://github.com/swarmpit/swarmpit/blob/master/src/clj/swarmpit/dockerhub/client.clj#L7) Maybe these queries are cached somehow for some time, need to check documentation ..

**Comment by lumir-mrkva** [comment] 2017-11-26 10:09
@derPuntigamer we're no longer filtering out public repositories from docker user repository searches (second tab), there should be docker api more up to date.

**Comment by nohaapav** [comment] 2018-01-03 09:31
I've deleted my private repo from dockerhub & since then there is no record in search. Working as expected. Closing.

**Closed by nohaapav** 2018-01-03 09:31 UTC
