### ISSUE TITLE
Unable to save change to service based on image from private Dockerhub repo.

### ISSUE THREAD

**Issue by mpsmith** [swarmpit/swarmpit#203] opened 2018-02-02 21:45 UTC
---------------------------------------------------
BUG REPORT
---------------------------------------------------

**Description**

When I attempt to edit and save a service that is using an image from a private Dockerhub repo, the web UI displays an error "Service update failed. Reason: authentication required".

**Steps to reproduce the issue:**
1.  Deploy Swarmpit 1.3 to a swarm 
2.  Login to swarmpit as admin.
2.  Created a shared developer role/account (user access level) in Swarmpit.
3.  Deploy a service using an image from a private dockerhub repo. (deployed from outside Swarmpit)
4.  Login to swarmpit as developer role/account.
5.  Edit the service.  
6.  Change replicas value
7.  Attempt to save.

**What happens:**
It displays an error on the bottom of the screen "Service update failed. Reason: authentication required". 

**What should happen:**
It should allow saving the service.

**Additional information (e.g. docker version, cluster setup,...):**
docker version: 17.09.1-ce

**Comment by johnjelinek** [comment] 2018-02-02 21:50
Looks like https://github.com/swarmpit/swarmpit/pull/152 may be a stopgap to fix this.

**Comment by nohaapav** [comment] 2018-02-02 23:09
@mpsmith First off all please update to swarmpit 1.3.1. There has been different repository management introduced fixing couple of issues.

Regarding issue: This is not bug but wanted change/behaviour.

Please check if user with user role has access to dockerhub private account. Even direct (created directly by user) or shared (created by any swarmpit user with public flag).

@johnjelinek #152 is different issue. Solving problem with registry which has blocked `/_catalog` api due to permissions so we can't prefetch list of images so must be enter manually.

**Comment by johnjelinek** [comment] 2018-02-03 00:30
i was able to reproduce this issue in `1.3.1`. The fix was to delete the `swarmpit_db` data volume and redeploy the service. This started working after scorched earth.

**Comment by nohaapav** [comment] 2018-02-03 09:09
I see where the problem was in your case @johnjelinek.

I forgot to include dockerhub distribution migration script within https://github.com/swarmpit/swarmpit/issues/197. 

In new dockerhub dist. management we are matching repository account based on namespaces and these are not part of dockerhub distribution record if version < 1.3.1. If you delete dockerhub account and create new one namespaces are fetched and everything works well. No need to delete whole volume but the result is pretty much same -> you are forced to recreate dockerhub distribution.

We will need to create as well some synchro job or button in case your docker account data has been changed because now the account data are fetched within distribution creation process.

**Comment by nohaapav** [comment] 2018-02-03 09:46
@mpsmith Please try to delete dockerhub distribution and recreate if you matching correct distribution access already and getting 401. This should make it work as described above.

**Comment by mpsmith** [comment] 2018-02-06 16:50
@nohaapav This worked for us.  Thanks!

**Comment by nohaapav** [comment] 2018-02-08 11:36
Good to hear. Closing then.

**Closed by nohaapav** 2018-02-08 11:36 UTC

**Comment by z-tc** [comment] 2018-06-06 11:34
I am running version 1.5-24ec1f9, created new user, logged in as that user, removed admin user. After i try do redeploy service, i get: Service redeploy failed. authentication required. Any idea?

**Comment by nohaapav** [comment] 2018-06-06 12:03
@z-tc do you have dockerhub account defined for new user ?

**Comment by z-tc** [comment] 2018-06-06 12:58
aah, thanks, that was missing!

**Comment by nohaapav** [comment] 2018-06-06 14:59
@z-tc yeah sorry .. we're going to create swarmpit documentation once 1.5 release is done. This error is anyway from registry / dockerhub .. If there is authentication error it always means that some credentials/account info is missing. But yeah good point that error message should be more descriptive in this case.

**Comment by junebug12851** [comment] 2020-06-02 12:21
I'm having the same issue, I've uploaded some images to Docker Hub but have them private. I've correctly linked it in the Registries and and I've marked the registry entry in swarmpit public even though I'm the only user. This also means I'm an admin.

I can deploy a new stack using a private Docker Hub image just fine, the issue comes in when I want to make any changes to the services in the stack. It errors out and tells me `Service update failed. No matching registry linked with Swarmpit`. The only way I can make changes is to edit the compose file for the whole stack which forces a stack-wide re-deploy which is very annoying.

I see 2 mentioned solutions on here:

* swarmpit_db data volume
* delete dockerhub distribution and recreate

The first I'm not sure if that really works or not and I don't want to mess anything up. The second I don't know what that means.

Are any of those solutions good or should I do something else?
