### ISSUE TITLE
I have issue with services creation. "mariadb:latest@" is not a valid repository/tag

### ISSUE THREAD

**Issue by Focusz** [swarmpit/swarmpit#687] opened 2024-04-19 10:02 UTC
BUG REPORT

**Steps to reproduce the issue:**
1. Create a new Service. (Example mariadb)
2. Enter version in Tag input value. (Example latest)
3. Then Next

**What happens:**
Dialog will show:
Service creation failed. rpc error: code = InvalidArgument desc = ContainerSpec: "mariadb:latest@" is not a valid repository/tag

![image](https://github.com/swarmpit/swarmpit/assets/4957690/263e7268-9ab6-4db2-83fe-e64d0f8027cf)

**Additional information (e.g. docker version, cluster setup,...):**

Server: Docker Engine - Community
 Engine:
  Version:          26.0.2
  API version:      1.45 (minimum version 1.24)
  Go version:       go1.21.9
  Git commit:       7cef0d9
  Built:            Thu Apr 18 16:26:06 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.31
  GitCommit:        e377cd56a71523140ca6ae87e30244719194a521
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**Comment by mrq1911** [comment] 2024-04-24 08:53
can confirm this is an issue for some images. 

as an workaround, you can edit stack

**Comment by mrq1911** [comment] 2024-04-24 08:57
duplicate of #676

**Closed** 2024-04-24 08:58 UTC
