### ISSUE TITLE
Unable to install swarmpit - swarmpit_app task is never started

### ISSUE THREAD

**Issue by mgutkin** [swarmpit/swarmpit#542] opened 2020-07-22 18:30 UTC
---------------------------------------------------
BUG REPORT
---------------------------------------------------
We are unable to install swarmpit to monitor an existing swarm cluster. 
When we run the install command "docker stack deploy -c docker-compose.yml swarmpit && docker events" or "docker stack deploy -c docker-compose.yml swarmpit" everything seems to be fine except swarmpit_app container is never deployed:
mm1yphqzzzx1        swarmpit_app         replicated          0/1                 swarmpit/swarmpit:latest                                                                                                     
n3346ydjbcll        swarmpit_db          replicated          1/1                 couchdb:2.3.0                                                                                                                
tmdi1mqg03un        swarmpit_influxdb    replicated          1/1                 influxdb:1.7     

**Steps to reproduce the issue:**
We get the same result every time we run the install command

**What happens:**
swarmpit_app container never deploys

**What should happen:**

**Additional information (e.g. docker version, cluster setup,...):**
Docker version 19.03.6-ce, build 369ce74
The cluster consists of 3 managers (EC2/Amazon Linux 2 ) and about 50 workers (ubuntu 18.04). 

The only errors we see in journalctl are these which probably not relevant:
Jul 22 18:22:55 ip-10-75-1-31.ec2.internal dockerd[11901]: http: TLS handshake error from 10.75.1.62:7892: EOF
Jul 22 18:22:56 ip-10-75-1-31.ec2.internal dockerd[11901]: time="2020-07-22T18:22:56.790835697Z" level=warning msg="grpc: Server.Serve failed to complete security handshake from \"10.75.1.62:1165\": EOF" module=grpc
Jul 22 18:22:56 ip-10-75-1-31.ec2.internal dockerd[11901]: time="2020-07-22T18:22:56.872102006Z" level=warning msg="grpc: Server.Serve failed to complete security handshake from \"10.75.1.62:20249\": EOF" module=grpc
Jul 22 18:22:57 ip-10-75-1-31.ec2.internal dockerd[11901]: http: TLS handshake error from 10.75.1.62:65122: EOF
Jul 22 18:22:57 ip-10-75-1-31.ec2.internal dockerd[11901]: time="2020-07-22T18:22:57.833787386Z" level=warning msg="grpc: Server.Serve failed to complete security handshake from \"10.75.1.62:35092\": EOF" module=grpc
Jul 22 18:22:58 ip-10-75-1-31.ec2.internal dockerd[11901]: http: TLS handshake error from 10.75.1.62:10859: EOF
Jul 22 18:22:59 ip-10-75-1-31.ec2.internal dockerd[11901]: time="2020-07-22T18:22:59.130189231Z" level=warning msg="grpc: Server.Serve failed to complete security handshake from \"10.75.1.62:17994\": EOF" module=grpc
lines 75-101/101 (END)

SERVICE INSPECT:
docker service inspect swarmpit_app produces the following output:
[
    {
        "ID": "mm1yphqzzzx12qoqkil25kj7k",
        "Version": {
            "Index": 100447
        },
        "CreatedAt": "2020-07-22T18:05:48.351721156Z",
        "UpdatedAt": "2020-07-22T18:05:48.351721156Z",
        "Spec": {
            "Name": "swarmpit_app",
            "Labels": {
                "com.docker.stack.image": "swarmpit/swarmpit:latest",
                "com.docker.stack.namespace": "swarmpit"
            },
            "TaskTemplate": {
                "ContainerSpec": {
                    "Image": "swarmpit/swarmpit:latest@sha256:c7cb161a54e3b2257c9efc33d868b39329355d09f83d456b3e7dfc299b04fa1a",
                    "Labels": {
                        "com.docker.stack.namespace": "swarmpit"
                    },
                    "Env": [
                        "SWARMPIT_DB=http://db:5984",
                        "SWARMPIT_INFLUXDB=http://influxdb:8086"
                    ],
                    "Privileges": {
                        "CredentialSpec": null,
                        "SELinuxContext": null
                    },
                    "Mounts": [
                        {
                            "Type": "bind",
                            "Source": "/var/run/docker.sock",
                            "Target": "/var/run/docker.sock",
                            "ReadOnly": true
                        }
                    ],
                    "StopGracePeriod": 10000000000,
                    "DNSConfig": {},
                    "Isolation": "default"
                },
                "Resources": {
                    "Limits": {
                        "NanoCPUs": 500000000,
                        "MemoryBytes": 1073741824
                    },
                    "Reservations": {
                        "NanoCPUs": 250000000,
                        "MemoryBytes": 536870912
                    }
                },
                "RestartPolicy": {
                    "Condition": "any",
                    "Delay": 5000000000,
                    "MaxAttempts": 0
                },
                "Placement": {
                    "Constraints": [
                        "node.role == manager"
                    ],
                    "Platforms": [
                        {
                            "Architecture": "amd64",
                            "OS": "linux"
                        },
                        {
                            "Architecture": "arm64",
                            "OS": "linux"
                        },
                        {
                            "OS": "linux"
                        },
                        {
                            "OS": "linux"
                        }
                    ]
                },
                "Networks": [
                    {
                        "Target": "0lxn32augmcnzoz5iffzqnsob",
                        "Aliases": [
                            "app"
                        ]
                    }
                ],
                "ForceUpdate": 0,
                "Runtime": "container"
            },
            "Mode": {
                "Replicated": {
                    "Replicas": 1
                }
            },
            "UpdateConfig": {
                "Parallelism": 1,
                "FailureAction": "pause",
                "Monitor": 5000000000,
                "MaxFailureRatio": 0,
                "Order": "stop-first"
            },
            "RollbackConfig": {
                "Parallelism": 1,
                "FailureAction": "pause",
                "Monitor": 5000000000,
                "MaxFailureRatio": 0,
                "Order": "stop-first"
            },
            "EndpointSpec": {
                "Mode": "vip",
                "Ports": [
                    {
                        "Protocol": "tcp",
                        "TargetPort": 8080,
                        "PublishedPort": 888,
                        "PublishMode": "ingress"
                    }
                ]
            }
        },
        "Endpoint": {
            "Spec": {}
        }
    }
]
[ec

LOGS:
"docker service logs swarmpit_app " doesn't produce any output

NODE PS:
[ec2-user@ip-10-75-1-31 ~]$ docker node ps 
ID                  NAME                                         IMAGE               NODE                         DESIRED STATE       CURRENT STATE          ERROR                              PORTS
j5yr7tqpdp7g        healthchecks.g2mtpt46ovy7cgx9a1oakusjf       nginx:alpine        ip-10-75-1-31.ec2.internal   Running             Running 6 weeks ago                                       
sd5wdorhp3tb         \_ healthchecks.g2mtpt46ovy7cgx9a1oakusjf   nginx:alpine        ip-10-75-1-31.ec2.internal   Shutdown            Rejected 7 weeks ago   "cannot create a swarm scoped …"   
tr8yk43tkz0n         \_ healthchecks.g2mtpt46ov

**Comment by rarous** [comment] 2020-08-20 12:15
@mgutkin as workaround: try to downscale managers to 1 and then install Swarmpit. Then you can upscale managers as desired. It happened to me this week and this worked for me. We will investigate what's wrong when there are more than one managers.

**Comment by rarous** [comment] 2020-08-20 12:22
Duplicate of #424

**Closed by rarous** 2020-08-20 12:22 UTC
Labels: kind/bug
