### ISSUE TITLE
Service Update: Empty Host Port returns NullPointerException

### ISSUE THREAD

**Issue by johnjelinek** [swarmpit/swarmpit#206] opened 2018-02-13 20:55 UTC
---------------------------------------------------
BUG REPORT
---------------------------------------------------

**Description**

There are some services that were created without swarmpit and when I go to update them, I see a 500 status code and the message "Service update failed. Reason:"

HTTP response body is:
```
{"cause":null,"via":[{"type":"java.lang.NullPointerException","message":null}],"trace":[]}
```

**Steps to reproduce the issue:**
1. Login to swarmpit as admin
2. Browse to existing service
3. Update replica set from 1 to 0

**What happens:**

`Service update failed. Reason:`

**What should happen:**

Service should be updated

**Additional information (e.g. docker version, cluster setup,...):**

```
Client:
 Version:	17.12.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	c97c6d6
 Built:	Wed Dec 27 20:10:14 2017
 OS/Arch:	linux/amd64

Server:
 Engine:
  Version:	17.12.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	c97c6d6
  Built:	Wed Dec 27 20:12:46 2017
  OS/Arch:	linux/amd64
  Experimental:	false
```

```
xntr74bgt8cq        swarmpit_app                                            replicated          1/1                 swarmpit/swarmpit:1.3.1                                             *:888->8080/tcp
ufz5ck0rg31t        swarmpit_db                                             replicated          1/1                 klaemo/couchdb:2.0.0
zhhzxv2m9o9m        swarmpit_event-collector                                global              6/6                 swarmpit/event-collector:latest
```

**Comment by nohaapav** [comment] 2018-02-13 22:54
@johnjelinek Could you provide some more info e.g. command/compose of how services were created. Not able to reproduce the issue.

**Comment by robertkeizer** [comment] 2018-02-19 02:46
I'm seeing the same thing. Screenshots for a bit more context.

Docker version `17.12.0-ce`.

Running swarmpit master as of this time; commit `473144baf1549b98b170e80836b3406458f64835`

<img width="1063" alt="screen shot 2018-02-18 at 8 45 21 pm" src="https://user-images.githubusercontent.com/339303/36360782-97cba25a-14ec-11e8-8044-efa2d8e93100.png">
<img width="1376" alt="screen shot 2018-02-18 at 8 45 32 pm" src="https://user-images.githubusercontent.com/339303/36360783-97ec46ae-14ec-11e8-8ff7-a52180fbdf91.png">

**Comment by nohaapav** [comment] 2018-02-19 09:01
@robertkeizer Could you provide services inspect. Looks like some mapping issue but can't say exactly  as don't see context.

**Comment by johnjelinek** [comment] 2018-02-19 19:02
@nohaapav: services were originally created from the CLI, `docker service create ...`

**Comment by johnjelinek** [comment] 2018-02-19 21:59
I upgraded to docker-ce `18.02`, and was able to reproduce this:

service created like this:
```
docker service create --detach=true \
  --with-registry-auth \
  --name installation-services-devpreview-blue \
  --network proxy \
  --constraint node.role==worker \
  --restart-condition=none \
  --log-driver=splunk \
  --log-opt splunk-format=raw \
  --log-opt splunk-url=redacted \
  --log-opt splunk-insecureskipverify=redacted \
  --log-opt splunk-index=redacted \
  --log-opt splunk-source=installation-services-devpreview \
  --log-opt splunk-token=redacted \
  --log-opt splunk-sourcetype=redacted \
  --log-opt tag=\"\" \
  --env DEPLOYMENT_STACK=preview \
  --env SERVICE_TAGS=devpreview \
  --env DEPLOYMENT_ENVIRONMENT=development \
  --secret source=redacted,target=redacted \
  --secret source=redacted,target=redacted \
  --secret source=redacted,target=redacted \
  --secret source=redacted,target=redacted \
  --secret source=redacted,target=redacted  \
  containerstore/installation-services:0.10.1-1-30d7311
```

Here's the request equivalent the browser makes:

```
curl 'http://dfw-sbx-swm-m-1:888/services/qkkb1xh4ls7enbfemjgyc5kxf' \
  -H 'Pragma: no-cache' \
  -H 'Origin: http://dfw-sbx-swm-m-1:888' \
  -H 'Accept-Encoding: gzip, deflate' \
  -H 'Accept-Language: en-US,en;q=0.9' \
  -H 'Authorization: Bearer redacted' \
  -H 'Content-Type: application/json' \
  -H 'Accept: application/transit+json, application/transit+transit, application/json, text/plain, text/html, */*' \
  -H 'Cache-Control: no-cache' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36' \
  -H 'Cookie: _ga=redacted' \
  -H 'Connection: keep-alive' \
  -H 'Referer: http://dfw-sbx-swm-m-1:888/' \
  --data-binary '{
    "labels": [{
        "name": "traefik.frontend.rule",
        "value": "Host:installation-services-v2.devpreview.containerstore.com"
    }, {
        "name": "traefik.port",
        "value": "8080"
    }],
    "repository": {
        "name": "containerstore/installation-services",
        "tag": "0.10.1-1-30d7311",
        "image": "containerstore/installation-services:0.10.1-1-30d7311",
        "imageDigest": "sha256:9fc1541b5fa560395f120cb282ae4dc4c463dc8f62cb6ec06bde2ecf54314b46"
    },
    "mounts": [],
    "secrets": [{
        "secretName": "redacted",
        "secretTarget": "redacted"
    }, {
        "secretName": "redacted",
        "secretTarget": "redacted"
    }, {
        "secretName": "redacted",
        "secretTarget": "redacted"
    }, {
        "secretName": "redacted",
        "secretTarget": "redacted"
    }, {
        "secretName": "redacted",
        "secretTarget": "redacted"
    }],
    "mode": "replicated",
    "variables": [{
        "name": "DEPLOYMENT_STACK",
        "value": "preview"
    }, {
        "name": "SERVICE_TAGS",
        "value": "devpreview"
    }, {
        "name": "DEPLOYMENT_ENVIRONMENT",
        "value": "development"
    }],
    "networks": [{
        "networkName": "proxy",
        "serviceAliases": null
    }],
    "ports": [{
        "containerPort": 8080,
        "protocol": "tcp",
        "hostPort": null
    }],
    "logdriver": {
        "name": "splunk",
        "opts": [{
            "name": "splunk-format",
            "value": "raw"
        }, {
            "name": "splunk-index",
            "value": "redacted"
        }, {
            "name": "splunk-insecureskipverify",
            "value": "redacted"
        }, {
            "name": "splunk-source",
            "value": "installation-services-devpreview"
        }, {
            "name": "splunk-sourcetype",
            "value": "redacted"
        }, {
            "name": "splunk-token",
            "value": "redacted"
        }, {
            "name": "splunk-url",
            "value": "redacted"
        }, {
            "name": "tag",
            "value": ""
        }]
    },
    "replicas": 0,
    "deployment": {
        "update": {
            "parallelism": 1,
            "delay": 0,
            "failureAction": "pause"
        },
        "forceUpdate": 0,
        "restartPolicy": {
            "condition": "any",
            "delay": 5,
            "attempts": 2
        },
        "rollback": {
            "parallelism": 1,
            "delay": 0,
            "failureAction": "pause"
        },
        "rollbackAllowed": true,
        "autoredeploy": null,
        "placement": [{
            "rule": "node.role==worker"
        }]
    },
    "stack": null,
    "serviceName": "installation-services-devpreview-blue",
    "version": 4433,
    "resources": {
        "reservation": {
            "cpu": 0,
            "memory": 0
        },
        "limit": {
            "cpu": 0,
            "memory": 0
        }
    },
    "configs": null
}' --compressed
```
and response `500 Internal Server Error`:
```
{
    "cause": null,
    "via": [{
        "type": "java.lang.NullPointerException",
        "message": null,
        "at": ["clojure.lang.Numbers", "ops", "Numbers.java", 1013]
    }],
    "trace": [
        ["clojure.lang.Numbers", "ops", "Numbers.java", 1013],
        ["clojure.lang.Numbers", "gt", "Numbers.java", 229],
        ["clojure.lang.Numbers", "gt", "Numbers.java", 3864],
        ["swarmpit.docker.mapper.outbound$__GT_service_ports$fn__5810", "invoke", "outbound.clj", 28],
        ["clojure.core$filter$fn__6893", "invoke", "core.clj", 2790],
        ["clojure.lang.LazySeq", "sval", "LazySeq.java", 40],
        ["clojure.lang.LazySeq", "seq", "LazySeq.java", 49],
        ["clojure.lang.RT", "seq", "RT.java", 525],
        ["clojure.core$seq__6407", "invokeStatic", "core.clj", 137],
        ["clojure.core$map$fn__6866", "invoke", "core.clj", 2719],
        ["clojure.lang.LazySeq", "sval", "LazySeq.java", 40],
        ["clojure.lang.LazySeq", "seq", "LazySeq.java", 49],
        ["clojure.lang.RT", "seq", "RT.java", 525],
        ["clojure.core$seq__6407", "invokeStatic", "core.clj", 137],
        ["clojure.core.protocols$seq_reduce", "invokeStatic", "protocols.clj", 24],
        ["clojure.core.protocols$fn__9111", "invokeStatic", "protocols.clj", 75],
        ["clojure.core.protocols$fn__9111", "invoke", "protocols.clj", 75],
        ["clojure.core.protocols$fn__9057$G__9052__9070", "invoke", "protocols.clj", 13],
        ["clojure.core$reduce", "invokeStatic", "core.clj", 6704],
        ["clojure.core$into", "invokeStatic", "core.clj", 6771],
        ["clojure.core$into", "invoke", "core.clj", 6763],
        ["swarmpit.docker.mapper.outbound$__GT_service_ports", "invokeStatic", "outbound.clj", 33],
        ["swarmpit.docker.mapper.outbound$__GT_service_ports", "invoke", "outbound.clj", 25],
        ["swarmpit.docker.mapper.outbound$__GT_service", "invokeStatic", "outbound.clj", 221],
        ["swarmpit.docker.mapper.outbound$__GT_service", "invoke", "outbound.clj", 198],
        ["swarmpit.api$update_service", "invokeStatic", "api.clj", 566],
        ["swarmpit.api$update_service", "invoke", "api.clj", 562],
        ["swarmpit.handler$fn__15752$fn__15754", "invoke", "handler.clj", 159],
        ["bidi.ring$fn__19108", "invokeStatic", "ring.clj", 20],
        ["bidi.ring$fn__19108", "invoke", "ring.clj", 17],
        ["bidi.ring$fn__19093$G__19088__19102", "invoke", "ring.clj", 12],
        ["bidi.ring$make_handler$fn__19113", "invoke", "ring.clj", 37],
        ["ring.middleware.resource$wrap_resource$fn__18256", "invoke", "resource.clj", 28],
        ["ring.middleware.resource$wrap_resource$fn__18256", "invoke", "resource.clj", 28],
        ["buddy.auth.accessrules$wrap_access_rules$fn__17350", "invoke", "accessrules.clj", 347],
        ["swarmpit.server$wrap_client_exception$fn__19463", "invoke", "server.clj", 25],
        ["swarmpit.server$wrap_fallback_exception$fn__19466", "invoke", "server.clj", 33],
        ["swarmpit.authentication$wrap_authentication$fn__18505", "invoke", "authentication.clj", 21],
        ["swarmpit.server$wrap_path_params$fn__19470", "invoke", "server.clj", 42],
        ["ring.middleware.json$wrap_json_params$fn__17559", "invoke", "json.clj", 72],
        ["ring.middleware.json$wrap_json_response$fn__17571", "invoke", "json.clj", 87],
        ["ring.middleware.flash$wrap_flash$fn__17616", "invoke", "flash.clj", 35],
        ["ring.middleware.session$wrap_session$fn__17984", "invoke", "session.clj", 103],
        ["ring.middleware.keyword_params$wrap_keyword_params$fn__18016", "invoke", "keyword_params.clj", 35],
        ["ring.middleware.nested_params$wrap_nested_params$fn__18074", "invoke", "nested_params.clj", 86],
        ["ring.middleware.multipart_params$wrap_multipart_params$fn__18204", "invoke", "multipart_params.clj", 133],
        ["ring.middleware.params$wrap_params$fn__18228", "invoke", "params.clj", 64],
        ["ring.middleware.cookies$wrap_cookies$fn__17881", "invoke", "cookies.clj", 161],
        ["ring.middleware.absolute_redirects$wrap_absolute_redirects$fn__18357", "invoke", "absolute_redirects.clj", 47],
        ["ring.middleware.resource$wrap_resource$fn__18256", "invoke", "resource.clj", 28],
        ["ring.middleware.content_type$wrap_content_type$fn__18322", "invoke", "content_type.clj", 30],
        ["ring.middleware.default_charset$wrap_default_charset$fn__18337", "invoke", "default_charset.clj", 31],
        ["ring.middleware.not_modified$wrap_not_modified$fn__18298", "invoke", "not_modified.clj", 52],
        ["ring.middleware.x_headers$wrap_x_header$fn__17586", "invoke", "x_headers.clj", 22],
        ["ring.middleware.x_headers$wrap_x_header$fn__17586", "invoke", "x_headers.clj", 22],
        ["ring.middleware.x_headers$wrap_x_header$fn__17586", "invoke", "x_headers.clj", 22],
        ["ring.middleware.gzip$wrap_gzip$fn__18444", "invoke", "gzip.clj", 94],
        ["org.httpkit.server.HttpHandler", "run", "RingHandler.java", 91],
        ["java.util.concurrent.Executors$RunnableAdapter", "call", "Executors.java", 511],
        ["java.util.concurrent.FutureTask", "run", "FutureTask.java", 266],
        ["java.util.concurrent.ThreadPoolExecutor", "runWorker", "ThreadPoolExecutor.java", 1142],
        ["java.util.concurrent.ThreadPoolExecutor$Worker", "run", "ThreadPoolExecutor.java", 617],
        ["java.lang.Thread", "run", "Thread.java", 745]
    ]
}
```

**Comment by johnjelinek** [comment] 2018-02-19 22:11
ah, looks like `"hostPort": null` is causing the issue here.

**Comment by johnjelinek** [comment] 2018-02-19 22:18
Here I see the service has a host port:
```
docker service ps installation-services-devpreview-blue
ID                  NAME                                          IMAGE                                                   NODE                DESIRED STATE       CURRENT STATE             ERROR               PORTS
s92m1yxg72bk        installation-services-devpreview-blue.1       containerstore/installation-services:0.10.1-1-30d7311   dfw-sbx-swm-w-1     Running             Running 44 minutes ago                        *:32768->8080/tcp
```

**Comment by johnjelinek** [comment] 2018-02-19 22:23
This command is used to update the host port:
```
docker service update \
            --publish-add target=32768,mode=host \
            installation-services-devpreview-blue
```

**Comment by johnjelinek** [comment] 2018-02-19 22:26
I've confirmed that if I add a `host port` in the UI, it's able to save ... seems like maybe some UI-level validation could help there if it can't figure it out from querying the docker engine.

**Comment by nohaapav** [comment] 2018-02-20 12:20
@johnjelinek Thanks for debugging. I've check the issue bit closer and the problem with npe is cause unfortunately by wrong endpoint mapping. We should map ports from:

`[:Endpoint :Ports] ` 
instead of
`[:Spec :EndpointSpec :Ports]`

In case there is no published port, nil is returned which cause the issue. Once mapping is fixed there will be no item in ports coll if port not published so no NPE will be thrown. There won't be even any record mentioning such port in UI as well.

**Comment by nohaapav** [comment] 2018-02-20 16:29
@johnjelinek should be fixed with https://github.com/swarmpit/swarmpit/commit/a9fecda57cde7f4ab85a11e623be34c4f4dba3e7

Please check.

**Comment by johnjelinek** [comment] 2018-02-20 22:34
ok, so, this change allows me to update the service without error, but it doesn't hold onto the original state. If I set the replica set back to 1, the original port configuration settings are missing.

**Comment by nohaapav** [comment] 2018-02-21 10:23
@johnjelinek i need to to check how docker handle this .. because even if i omit PublishPort while calling service update API, some random publish port is exposed (e.g. 30010). That's the reason why i'm removing port item from spec if there is no PublishPort associated on update.

Is there any reason to have just publish-add within the service without exposed port anyway? You can reach service by its target port by default if within same network.

**Comment by nohaapav** [comment] 2018-03-09 10:52
@johnjelinek I'm going to close this issue because of inactivity. NPE is not an issue anymore, we can discuss in separate thread publish state change and possible issues regarding that if any.

**Closed by nohaapav** 2018-03-09 10:52 UTC
Labels: kind/bug
