### ISSUE TITLE
User stack Permission

### ISSUE THREAD

**Issue by thiagocpv** [swarmpit/swarmpit#593] opened 2021-04-10 00:29 UTC
Hi,

Is there a way to just the user see the own stack or service?
When login with user role, the user has the same role than admin has.

Swarmpit version: 1.10-38ffbe0

Thanks.

Thiago

**Comment by nohaapav** [comment] 2021-04-11 17:15
No this is not possible yet.

Currently only difference is that admin can create users, user not.

**Comment by thiagocpv** [comment] 2021-04-11 23:41
Ok, thanks for the information.
I will waiting for this feature to start the use.

**Comment by nohaapav** [comment] 2021-05-29 07:33
Duplicate of https://github.com/swarmpit/swarmpit/issues/94

**Closed by nohaapav** 2021-05-29 07:33 UTC

**Comment by thiagocpv** [comment] 2023-02-09 20:28
@NeilInnes wow! I will do the tests soon.
Thx for the awesome work.
